apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prime-developers-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
    - hosts:
        - primedevelopers.com
        - api.primedevelopers.com
      secretName: prime-developers-tls
  rules:
    - host: primedevelopers.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prime-frontend-service
                port:
                  number: 80
    - host: api.primedevelopers.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prime-backend-service
                port:
                  number: 5000
