export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  SALES_MANAGER = 'SALES_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  AGENT = 'AGENT',
  CUSTOMER = 'CUSTOMER',
  GUEST = 'GUEST'
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION'
}

export enum PropertyType {
  RESIDENTIAL_APARTMENT = 'RESIDENTIAL_APARTMENT',
  LUXURY_VILLA = 'LUXURY_VILLA',
  COMMERCIAL_OFFICE = 'COMMERCIAL_OFFICE',
  RETAIL_SHOP = 'RETAIL_SHOP',
  PLOTTED_DEVELOPMENT = 'PLOTTED_DEVELOPMENT',
  PENTHOUSE = 'PENTHOUSE'
}

export enum PropertyStatus {
  UPCOMING = 'UPCOMING',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  READY_TO_MOVE = 'READY_TO_MOVE',
  SOLD_OUT = 'SOLD_OUT'
}

export enum PlotStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  SOLD = 'SOLD',
  BLOCKED = 'BLOCKED'
}

export enum BookingStatus {
  PENDING = 'PENDING',
  TOKEN_PAID = 'TOKEN_PAID',
  AGREEMENT_SIGNED = 'AGREEMENT_SIGNED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}

export enum PaymentMethod {
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  CASH = 'CASH'
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  SITE_VISIT_SCHEDULED = 'SITE_VISIT_SCHEDULED',
  SITE_VISIT_COMPLETED = 'SITE_VISIT_COMPLETED',
  NEGOTIATION = 'NEGOTIATION',
  BOOKED = 'BOOKED',
  LOST = 'LOST'
}

export enum LeadPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum NotificationType {
  BOOKING_UPDATE = 'BOOKING_UPDATE',
  PAYMENT_DUE = 'PAYMENT_DUE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  LEAD_ASSIGNED = 'LEAD_ASSIGNED',
  SITE_VISIT_REMINDER = 'SITE_VISIT_REMINDER',
  CONSTRUCTION_UPDATE = 'CONSTRUCTION_UPDATE',
  SYSTEM = 'SYSTEM'
}
